global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "metrics-from-otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "otelcols-metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8888"]